import type { CustomerVoiceInput, DemoDataset } from "../../../types/revenue";

export const hotelDemoData: DemoDataset = {
  id: "korean-summer-hotel",
  industry: "Hospitality",
  language: "ko",
  name: "Korea Summer Hotel Demo",
  description:
    "Synthetic sample data for testing Review-to-Revenue AI with Korean summer vacation hotel reviews.",
  reviewsText: [
    "8월 성수기라 가격이 높다는 건 이해하지만 오션뷰가 생각보다 옆쪽이라 가격 대비 만족도가 애매했습니다.",
    "객실은 청결했고 침구도 좋았지만 복도 소음과 옆방 대화 소리가 밤에 꽤 들렸습니다.",
    "조식 포함 패키지였는데 8시 이후에는 대기 줄이 길어서 아이와 함께 기다리기 힘들었습니다.",
    "수영장 이용 시간이 몰리니 썬베드와 탈의실이 너무 붐볐고 사전 안내가 더 자세했으면 했습니다.",
    "주차장 입구 안내가 부족해서 체크인 전부터 가족들이 차 안에서 오래 기다렸습니다.",
    "체크인 대기가 40분 정도 있었는데 성수기라면 모바일 사전 체크인 안내가 필요해 보였습니다.",
    "아이 동반 가족에게는 위치와 해변 접근성이 정말 좋았고 직원 안내도 친절했습니다.",
    "부모님을 모시고 갔는데 엘리베이터 동선과 주차 위치 설명이 부족해 처음에 헤맸습니다.",
    "커플 여행으로는 일출 뷰가 좋았지만 객실 타입별 뷰 차이를 예약 전에 더 명확히 알고 싶었습니다.",
    "사진에서 본 객실보다 실제 방이 조금 좁게 느껴졌고 욕실 사진도 더 정확했으면 합니다.",
    "추가 수영장 요금과 조식 업그레이드 비용을 예약 단계에서 한 번에 봤으면 좋겠습니다.",
    "청결은 만족했지만 밤에 아이들이 뛰는 소리 때문에 방음이 약하다는 느낌을 받았습니다.",
    "해변까지 걸어서 갈 수 있는 위치는 최고였고, 체크아웃 후 짐 보관 안내도 친절했습니다.",
    "가격은 부담됐지만 객실 청결과 직원 응대가 좋아서 가족 여행 만족도는 높았습니다.",
    "조식 뷔페 메뉴는 괜찮았지만 대기 시간과 혼잡도가 성수기에는 가장 큰 스트레스였습니다.",
    "오션뷰 객실이라고 예약했는데 저층 일부 뷰라 기대와 실제가 달랐습니다.",
    "주차 가능하다고만 적혀 있었고 늦게 도착하면 외부 주차장을 써야 한다는 안내가 부족했습니다.",
    "수영장은 아이들이 좋아했지만 피크 시간대 혼잡도를 미리 알려주면 더 좋겠습니다.",
    "프런트 직원은 친절했지만 체크인 순번 안내가 화면에 없어서 계속 물어봐야 했습니다.",
    "방은 깨끗하고 침대가 편했지만 에어컨 소음과 복도 소리가 거슬렸습니다.",
    "성수기 가격이라면 조식, 주차, 수영장, 뷰 차이에 대한 사전 설명이 더 필요합니다.",
    "가족 여행객에게는 키즈풀과 해변 접근성이 큰 장점이고, 부모 입장에서는 주차가 중요합니다.",
    "배우자와 가격 때문에 고민했지만 객실 컨디션과 위치 설명을 보고 예약했습니다.",
    "다른 호텔과 비교하다가 여기로 왔는데 청결과 친절한 안내는 확실히 좋았습니다.",
    "예약 전 문자로 체크인 대기 가능성과 조식 혼잡 시간대를 알려주면 신뢰가 더 생길 것 같습니다.",
    "총비용이 객실가보다 올라가는 구조라 추가비용 안내가 더 투명해야 합니다.",
    "아이와 함께 가기에는 좋지만 방음과 조식 대기 문제는 다시 예약할 때 고민될 것 같습니다.",
    "오션뷰 등급을 정면뷰, 측면뷰, 일부뷰로 나눠 설명해주면 기대 차이가 줄어들 것 같습니다.",
    "성수기라 주차와 체크인 대기가 가장 불편했고, 객실 청결은 만족스러웠습니다.",
    "가격이 비싼 만큼 조식 혼잡, 수영장 혼잡, 주차 안내까지 포함해서 비교하고 싶었습니다.",
    "예약 전에 가족 동선, 주차 위치, 방음 수준을 체크리스트로 받았다면 결정이 더 빨랐을 것 같습니다.",
    "상담 직원이 친절하게 객실뷰 차이와 해변 접근성을 설명해줘서 불안이 줄었습니다."
  ].join("\n"),
  competitorReviewsText: [
    "경쟁 호텔은 체크인 대기가 길었고 프런트 응답이 늦어 첫인상이 좋지 않았습니다.",
    "사진 속 객실은 넓어 보였는데 실제 객실은 좁고 뷰도 기대와 달랐습니다.",
    "예약 화면에는 저렴해 보였지만 현장에서 수영장과 조식 추가비용이 붙었습니다.",
    "방음이 약해서 옆방 TV 소리와 복도 소음이 밤새 들렸습니다.",
    "주차 안내가 부족해 외부 주차장까지 돌아가야 했고 가족들이 불편해했습니다.",
    "조식 대기가 길었는데 직원이 혼잡 시간대를 미리 안내하지 않았습니다.",
    "문의 답변이 하루 뒤에 와서 성수기 예약 결정을 다른 호텔로 바꿀 뻔했습니다.",
    "오션뷰라고 했지만 실제로는 건물 사이로 바다가 조금 보이는 수준이었습니다.",
    "수영장 사진은 좋아 보였지만 실제로는 사람이 너무 많아 이용하기 어려웠습니다.",
    "체크인 줄 관리가 안 되어 누가 먼저인지 계속 혼란스러웠습니다.",
    "추가 요금이 늦게 안내되어 총비용을 비교하기 어려웠습니다.",
    "직원 응대가 불친절했고 주차 문의에 정확한 답변을 받지 못했습니다.",
    "부모님과 함께 갔는데 엘리베이터 위치와 동선 안내가 부족했습니다.",
    "아이 동반 고객이 많은데 조식 좌석 안내가 미흡했습니다.",
    "해변 접근성은 좋았지만 객실 청결이 기대보다 부족했습니다.",
    "예약 전 사진과 실제 욕실 상태가 달라 신뢰가 떨어졌습니다.",
    "가격은 비슷한데 사전 안내가 부족해 계속 전화로 확인해야 했습니다.",
    "비교 중이던 다른 호텔보다 답변이 느려 예약을 망설였습니다.",
    "주차 가능이라고만 쓰여 있고 만차 시 대안 안내가 없었습니다.",
    "성수기에는 방음, 조식, 수영장 혼잡 정보가 꼭 필요하다고 느꼈습니다.",
    "프런트에서 체크인 지연 이유를 설명하지 않아 기다림이 더 길게 느껴졌습니다.",
    "총비용을 예약 전에 알 수 없어 결제 직전 보류했습니다."
  ].join("\n"),
  salesNotesText: [
    "김민지 / 네이버 톡톡 / 가족 4인 8월 둘째 주 / 오션뷰와 조식 포함 문의 / 예산 55만원 / 배우자와 상의 후 미응답 5일 / 가격 부담과 주차 걱정",
    "박준호 / 전화 / 커플 여행 / 고층 오션뷰 선호 / 예산 42만원 / 결제 직전 보류 / 뷰 등급 차이 설명 요청",
    "이서연 / 카카오 / 부모님 동반 / 엘리베이터 동선과 주차 문의 / 예산 60만원 / 비교 중 / 방음과 조식 대기 걱정",
    "최유진 / 홈페이지 / 아이 동반 가족 / 키즈풀과 조식 포함 문의 / 예산 70만원 / 미응답 4일 / 수영장 혼잡도 확인 원함",
    "정하늘 / 인스타 DM / 커플 여행 / 일출뷰와 해변 접근성 관심 / 예산 48만원 / Waiting / 사진과 실제 뷰 차이 질문",
    "윤성민 / 네이버 톡톡 / 가족 여행 / 주차와 체크인 대기 문의 / 예산 50만원 / Needs Follow-up / 성수기 도착 시간 고민",
    "오지은 / 전화 / 부모님 모시고 방문 / 조용한 객실 요청 / 예산 58만원 / No Response / 방음과 엘리베이터 동선 걱정",
    "한도윤 / 홈페이지 / 친구 3인 / 수영장 패키지 문의 / 예산 45만원 / Comparing / 추가비용과 총비용 비교 중",
    "문채원 / 카카오 / 가족 5인 / 객실 2개 예약 문의 / 예산 95만원 / Hot / 조식 좌석과 주차 확답 필요",
    "강지훈 / 전화 / 커플 기념일 / 오션뷰 업그레이드 문의 / 예산 65만원 / Contacted / 결제 링크 전달 전 뷰 설명 필요",
    "서아린 / 네이버 톡톡 / 아이 동반 / 조식 혼잡 시간 문의 / 예산 52만원 / Waiting / 배우자와 상의 예정",
    "임태오 / 인스타 DM / 성수기 2박 / 해변 접근성 관심 / 예산 80만원 / No Response / 다른 호텔과 비교 중",
    "배수아 / 홈페이지 / 부모님 동반 / 조용한 층 요청 / 예산 62만원 / Needs Follow-up / 방음과 객실 위치 걱정",
    "노현우 / 전화 / 가족 여행 / 수영장과 주차 포함 여부 / 예산 75만원 / Comparing / 총비용이 높아 보류",
    "홍다은 / 카카오 / 커플 여행 / 일부 오션뷰 객실 문의 / 예산 39만원 / Waiting / 가격 대비 뷰 만족도 질문",
    "신지아 / 네이버 톡톡 / 가족 여행 / 체크인 대기와 짐 보관 문의 / 예산 57만원 / Hot / 오늘 중 결제 가능성"
  ].join("\n"),
  leadCsv: [
    "name,channel,industry,interest,budget,lastContactDate,lastMessage,status,objection,urgency,potentialValue,notes",
    "김민지,Naver Talk,Hotel Booking,Family ocean view package,550000,2026-06-19,배우자와 상의 후 연락드릴게요,No Response,Family/Partner,High,550000,가격 부담과 주차 안내 필요",
    "박준호,Phone,Hotel Booking,Couple high-floor ocean view,420000,2026-06-22,결제 전에 뷰 차이를 더 알고 싶어요,Waiting,Information Gap,High,420000,오션뷰 등급 설명 필요",
    "이서연,Kakao,Hotel Booking,Parents trip parking and quiet room,600000,2026-06-18,다른 호텔도 보고 있어요,Comparing,Comparison Shopping,Medium,600000,방음 조식 주차 비교 중",
    "최유진,Website,Hotel Booking,Kids pool breakfast package,700000,2026-06-20,수영장 혼잡도가 걱정돼요,Needs Follow-up,Outcome Uncertainty,High,700000,아이 동반 가족",
    "정하늘,Instagram,Hotel Booking,Sunrise ocean view,480000,2026-06-21,사진과 실제 객실이 같은가요,Waiting,Trust Barrier,Medium,480000,사진과 실제 뷰 차이",
    "윤성민,Naver Talk,Hotel Booking,Parking and check-in timing,500000,2026-06-19,주차가 어려우면 고민됩니다,Needs Follow-up,Information Gap,High,500000,성수기 도착 안내 필요",
    "오지은,Phone,Hotel Booking,Quiet room for parents,580000,2026-06-17,부모님이 소음에 민감하세요,No Response,Outcome Uncertainty,Medium,580000,방음과 동선 설명 필요",
    "한도윤,Website,Hotel Booking,Pool package total cost,450000,2026-06-22,추가비용까지 총액이 궁금해요,Comparing,Price Concern,High,450000,수영장 조식 추가비용",
    "문채원,Kakao,Hotel Booking,Two rooms with breakfast,950000,2026-06-23,조식 좌석과 주차 확답되면 예약할게요,Hot,Information Gap,High,950000,결제 직전 리드",
    "강지훈,Phone,Hotel Booking,Anniversary ocean view upgrade,650000,2026-06-23,정면뷰면 바로 결제할게요,Hot,Information Gap,High,650000,뷰 등급 확인 필요",
    "서아린,Naver Talk,Hotel Booking,Family breakfast timing,520000,2026-06-20,배우자와 다시 이야기해볼게요,Waiting,Family/Partner,Medium,520000,조식 혼잡도 걱정",
    "임태오,Instagram,Hotel Booking,Beach access two nights,800000,2026-06-18,다른 곳과 가격 비교 중입니다,No Response,Comparison Shopping,Medium,800000,성수기 가격 비교",
    "배수아,Website,Hotel Booking,Quiet floor parents trip,620000,2026-06-19,방음이 괜찮은 객실이면 좋아요,Needs Follow-up,Outcome Uncertainty,Medium,620000,부모님 동반",
    "노현우,Phone,Hotel Booking,Family pool parking included,750000,2026-06-21,총비용이 생각보다 높네요,Comparing,Price Concern,High,750000,주차 수영장 추가비용 비교",
    "홍다은,Kakao,Hotel Booking,Partial ocean view couple trip,390000,2026-06-20,이 가격이면 뷰가 어느 정도인가요,Waiting,Price Concern,Medium,390000,가격 대비 뷰 기대",
    "신지아,Naver Talk,Hotel Booking,Check-in and luggage storage,570000,2026-06-23,대기만 짧으면 오늘 예약할게요,Hot,Timing Delay,High,570000,체크인 대기와 짐 보관"
  ].join("\n"),
  demoLabel: "Demo Data · Korean Summer Hotel Reviews"
};

export const hotelDemoInput: CustomerVoiceInput = {
  reviewsText: hotelDemoData.reviewsText,
  competitorReviewsText: hotelDemoData.competitorReviewsText,
  demoLabel: hotelDemoData.demoLabel,
  salesNotesText: hotelDemoData.salesNotesText,
  leadCsv: hotelDemoData.leadCsv,
  outputLanguage: "en"
};
